-- Snowflake user creation
-- Step 1: Use an admin role
USE ROLE ACCOUNTADMIN;

-- Step 2: Create the `transform` role and assign it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Step 3: Create a default warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Step 4: Create the `dbt` user and assign to the transform role
CREATE USER IF NOT EXISTS dbt
  PASSWORD=''
  LOGIN_NAME=''
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_NAMESPACE='MOVIELENS.RAW'
  COMMENT='DBT user used for data transformation';

ALTER USER dbt SET TYPE = LEGACY_SERVICE;

GRANT ROLE TRANSFORM TO USER dbt;

-- Step 5: Create a database and schema for the MovieLens project
CREATE DATABASE IF NOT EXISTS MOVIELENS;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.RAW;

-- Step 6: Grant permissions to the `transform` role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;

SELECT CURRENT_ACCOUNT(), CURRENT_USER();
SHOW USERS LIKE 'DBT';

SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();

SELECT CURRENT_ACCOUNT(), CURRENT_USER(), CURRENT_ROLE();
SHOW USERS LIKE 'DBT';
ALTER USER dbt SET PASSWORD = '';


USE WAREHOUSE COMPUTE_WH;
USE DATABASE MOVIELENS;
USE SCHEMA RAW;
CREATE OR REPLACE STAGE NETFLIXSTAGE
    URL = 's3://netflix-analyses-dataset'
    CREDENTIALS = (
        AWS_KEY_ID = ''
        AWS_SECRET_KEY = ''
    );

--copying the movies.csv from s3
CREATE OR REPLACE TABLE raw_movies (
    movieId INTEGER,
    title STRING,
    genres STRING
)

COPY INTO RAW_MOVIES
FROM '@NETFLIXSTAGE/movies.csv'
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);


---copying the links csv from s3
CREATE OR REPLACE TABLE raw_links (
    movieId INTEGER,
    imdbId INTEGER,
    tmdbId INTEGER
    
);
COPY INTO RAW_LINKS
FROM '@NETFLIXSTAGE/links.csv'
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

--copying the genome-tage from the s3

CREATE OR REPLACE TABLE raw_genome_tags (
    tagId INTEGER,
    tag STRING
)

COPY INTO RAW_GENOME_TAGS
FROM '@NETFLIXSTAGE/genome-tags.csv'
FILE_FORMAT =(
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

--COPYING GENOME-SCORES FROM S3
CREATE OR REPLACE TABLE RAW_GENOME_SCORES(
    movieId INTEGER,
    tagId INTEGER,
    relevance FLOAT
);
COPY INTO RAW_GENOME_SCORES
FROM '@NETFLIXSTAGE/genome-scores.csv'
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER =  1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

--copying the tags.csv from s3
CREATE OR REPLACE TABLE RAW_TAGS(
    userId INTEGER,
    movieId INTEGER,
    tag STRING,
    timestamp BIGINT
);

CREATE OR REPLACE FILE FORMAT RAW_TAGS
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

COPY INTO RAW_TAGS
FROM '@NETFLIXSTAGE/tags.csv'
FILE_FORMAT = (FORMAT_NAME = 'RAW_TAGS');
--COPYING FROM ratings.csv FROM S3
CREATE OR REPLACE TABLE RAW_RATINGS(
    userId INTEGER,
    movieId INTEGER,
    rating FLOAT,
    timestamp BIGINT
);

COPY INTO RAW_RATINGS
FROM '@NETFLIXSTAGE/ratings.csv'
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);




--TESTINGS 
SHOW STAGES LIKE 'NETFLIXSTAGE';
SELECT *  FROM raw_movies;
SELECT * FROM raw_links;
SELECT * FROM raw_genome_tags;
SELECT * FROM raw_tags;
SELECT * FROM raw_genome_scores;
SELECT * FROM raw_ratings;
